name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: apt install -y base-files bash coreutils grep libc-bin libc6:amd64 libpcre2-8-0:amd64 libpython3.14-stdlib:amd64 libselinux1:amd64 libzstd1:amd64 locales ncurses-base openssl python3.14 tzdata
      - name: Sync with uv
        run: uv sync --locked --no-dev --group tests
      - name: Prepare coverage directory
        run: mkdir coverage
      - name: Run test-files script
        run: uv run bash scripts/test-files.sh
      - name: Run test script
        run: uv run bash scripts/test.sh